name: GitHub Classroom Workflow - Figuras Geometricas

on:
  - push

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.8.1.0'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ hashFiles('**/figuras-geometricas.cabal') }}
          restore-keys: |
            ${{ runner.os }}-ghc-
      - name: Build
        run: cabal build --enable-tests
      - name: Run Autograding Tests
        uses: education/autograding@v1
