name: GitHub Classroom autograding

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  test:
    name: cabal test
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar GHC e Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.10.3.0"

      - name: Atualizar índice de pacotes
        run: cabal update

      - name: Construir o projeto
        run: cabal build all

      - name: Executar testes
        run: cabal test all
